/**
 * The 91 frames matched one by one between this ERP and the website,
 * generated once from docs/webid-seed.csv.
 *
 * Seeding updates by `erpProductId` (the ERP's own id), never by name.
 * `erpSku` and `erpName` are only there so a person can check each row.
 */
export type WebIdSeedRow = {
  webId: string;
  erpProductId: string;
  erpSku: string;
  erpName: string;
};

export const WEB_ID_SEED: WebIdSeedRow[] = [
  { webId: "MOAK-YEK-BLACK", erpProductId: "cmjsn4atb001gflka5moqk22d", erpSku: "YEK/BLK", erpName: "YEK - Black" },
  { webId: "MOAK-YEK-SAFARI", erpProductId: "cmjsn4ac2001fflkay7wvo6ye", erpSku: "YEK/SAFR", erpName: "YEK - Safari" },
  { webId: "MOAK-YEK-BROWN", erpProductId: "cmjsn49t8001eflkaoa8ey3pl", erpSku: "YEK/BRWN", erpName: "YEK - Brown" },
  { webId: "MOAK-DO-BLACK", erpProductId: "cmjsn49c4001dflkatzqf8i24", erpSku: "DO/BLK", erpName: "DO - Black" },
  { webId: "MOAK-DO-TRANSPARENT", erpProductId: "cmjsn48lb001cflka1cucicll", erpSku: "DO/TRNS", erpName: "DO - Transparent" },
  { webId: "MOAK-DO-BROWN", erpProductId: "cmjsn4840001bflkamb7hme2l", erpSku: "DO/BRWN", erpName: "DO - Brown" },
  { webId: "MOAK-SE-BROWN", erpProductId: "cmjsn47ms001aflkauxnqsuuy", erpSku: "SE/BRWN", erpName: "SE - Brown" },
  { webId: "MOAK-SE-BLACK", erpProductId: "cmjsn46tt0019flkaztgtxkem", erpSku: "SE/BLK", erpName: "SE - Black" },
  { webId: "MOAK-CHAR-BLACK", erpProductId: "cmjsn46820018flkaix034lam", erpSku: "CHAR/BLK", erpName: "CHAR - Black" },
  { webId: "MOAK-CHAR-TRANSPARENT", erpProductId: "cmjsn45r00017flka22780xo7", erpSku: "CHAR/TRNS", erpName: "CHAR -  Transparent" },
  { webId: "MOAK-PANJ-BLUE", erpProductId: "cmjsn45970016flka4irfmsrj", erpSku: "PANJ/BLUE", erpName: "PANJ - Blue" },
  { webId: "MOAK-PANJ-HAVANA", erpProductId: "cmjsn44l00015flkagbnz0tgu", erpSku: "PANJ/HAVANA", erpName: "PANJ - Havana" },
  { webId: "MOAK-PANJ-TRANSPARENT", erpProductId: "cmjsn43z80014flkaoe10cz31", erpSku: "PANJ/TRNS", erpName: "PANJ - Transparent" },
  { webId: "MOAK-HAFT-BLACK", erpProductId: "cmjsn43d00013flka3atwqrna", erpSku: "HAFT/BLK", erpName: "HAFT - Black" },
  { webId: "MOAK-HAFT-GREEN", erpProductId: "cmjsn42vl0012flkaaxhp7f4o", erpSku: "HAFT/GREN", erpName: "HAFT - Green" },
  { webId: "MOAK-HAFT-TRANSPARENT", erpProductId: "cmjsn42ec0011flkapk44vp86", erpSku: "HAFT/TRNS", erpName: "HAFT - Transparent" },
  { webId: "MOAK-HASHT-BLUE", erpProductId: "cmjsn41w50010flka5p4i4cwk", erpSku: "HASHT/BLUE", erpName: "HASHT - Blue" },
  { webId: "MOAK-HASHT-BROWN", erpProductId: "cmjsn41af000zflka1w4seubk", erpSku: "HASHT/BRWN", erpName: "HASHT - Brown" },
  { webId: "MOAK-265OW-BLACK", erpProductId: "cmjsn40oo000yflka1wyo6qy3", erpSku: "265W/BLK", erpName: "265ºW - Black" },
  { webId: "MOAK-265OW-BLUE", erpProductId: "cmjsn404r000xflkatpqbqpc3", erpSku: "265W/BLUE", erpName: "265ºW - Blue" },
  { webId: "MOAK-265OW-TRANSPARENT", erpProductId: "cmjsn3zgh000wflkac4vua9db", erpSku: "265W/TRNS", erpName: "265ºW - Transparent" },
  { webId: "MOAK-80OE-BLACK", erpProductId: "cmjsn3yss000vflkakc9jj1yj", erpSku: "80E/BLK", erpName: "80ºE - Black" },
  { webId: "MOAK-80OE-GREEN", erpProductId: "cmjsn3y96000uflka4ix3tqr5", erpSku: "80E/GREN", erpName: "80ºE - Green" },
  { webId: "MOAK-80OE-TRANSPARENT", erpProductId: "cmjsn3xl0000tflkaapkxdelg", erpSku: "80E/TRNS", erpName: "80ºE - Transparent" },
  { webId: "MOAK-230OW-HAVANA", erpProductId: "cmjsn3wyt000sflka5tcmo6r0", erpSku: "230W/HVNA", erpName: "230ºW - Havana" },
  { webId: "MOAK-230OW-YELLOW", erpProductId: "cmjsn3wal000rflka5vzr84qg", erpSku: "230W/YELO", erpName: "230ºW - Yellow" },
  { webId: "MOAK-230OW-BLACK", erpProductId: "cmjsn3vqy000qflka6ctdos59", erpSku: "230W/BLK", erpName: "230ºW - Black" },
  { webId: "MOAK-250OW-GREEN", erpProductId: "cmjsn3v97000pflka29w1322u", erpSku: "250W/GREN", erpName: "250ºW - Green" },
  { webId: "MOAK-250OW-RED", erpProductId: "cmjsn3ukq000oflkauwa4r1b7", erpSku: "250W/RED", erpName: "250ºW - Red" },
  { webId: "MOAK-250OW-BLACK", erpProductId: "cmjsn3twf000nflkaj22p6fas", erpSku: "250W/BLK", erpName: "250ºW - Black" },
  { webId: "MOAK-290OW-BROWN", erpProductId: "cmjsn3ta5000mflkay26z8ggt", erpSku: "290W/BRWN", erpName: "290ºW - Brown" },
  { webId: "MOAK-290OW-GREEN", erpProductId: "cmjsn3so4000lflka0ivqoaw1", erpSku: "290W/GREN", erpName: "290ºW - Green" },
  { webId: "MOAK-290OW-HAVANA", erpProductId: "cmjsn3rv7000kflkaxjoz2oo1", erpSku: "290W/HVNA", erpName: "290ºW - Havana" },
  { webId: "MOAK-300OW-BLACK", erpProductId: "cmjsn3r96000jflka37mjgtmm", erpSku: "300W/BLK", erpName: "300ºW - Black" },
  { webId: "MOAK-300OW-BLUE", erpProductId: "cmjsn3qpa000iflkabjr13i5y", erpSku: "300W/BLUE", erpName: "300ºW - Blue" },
  { webId: "MOAK-300OW-YELLOW", erpProductId: "cmjsn3q0u000hflkake2y7h8e", erpSku: "300W/YELO", erpName: "300ºW - Yellow" },
  { webId: "MOAK-310OW-BLACK", erpProductId: "cmjsn3pf1000gflka8oa6s5ea", erpSku: "310W/BLK", erpName: "310ºW - Black" },
  { webId: "MOAK-310OW-BROWN", erpProductId: "cmjsn3ov8000fflkatdtifwz2", erpSku: "310W/BRWN", erpName: "310ºW - Brown" },
  { webId: "MOAK-310OW-HAVANA", erpProductId: "cmjsn3o1w000eflka0k9y16r8", erpSku: "310W/HVNA", erpName: "310ºW - Havana" },
  { webId: "MOAK-320OW-BLACK", erpProductId: "cmjsn3nfn000dflkab6kx7o2i", erpSku: "320W/BLK", erpName: "320ºW - Black" },
  { webId: "MOAK-320OW-BLUE", erpProductId: "cmjsn3moo000cflkabdc3rsn1", erpSku: "320W/BLUE", erpName: "320ºW - Blue" },
  { webId: "MOAK-320OW-HAVANA", erpProductId: "cmjsn3m0h000bflkaplqli8i4", erpSku: "320W/HVNA", erpName: "320ºW - Havana" },
  { webId: "MOAK-SE-GREEN", erpProductId: "cmjsn3li5000aflka9m20cxap", erpSku: "SE/GREN", erpName: "SE - Green" },
  { webId: "MOAK-CHAR-HAVANA", erpProductId: "cmjsn3l0v0009flkajbwmyrur", erpSku: "CHAR/HAVANA", erpName: "CHAR -  Havana" },
  { webId: "MOAK-VERIDA-HAVANA", erpProductId: "cmjsn3kjc0008flkahf602qk6", erpSku: "VERIDA", erpName: "VERIDA" },
  { webId: "MOAK-STELLAN-BROWN", erpProductId: "cmjsn3k1x0007flkazy8yxaeo", erpSku: "STELLAN", erpName: "STELLAN" },
  { webId: "MOAK-KYRO-BLACK", erpProductId: "cmjsn3jg10006flkakcomajiq", erpSku: "KYRO", erpName: "KŶRO" },
  { webId: "MOAK-AETHEL-RED", erpProductId: "cmjsn3ist0005flkauua09x57", erpSku: "AETHEL", erpName: "AETHEL" },
  { webId: "MOAK-BRECK-BROWN", erpProductId: "cmjsn3i6y0004flkapb9nl3u8", erpSku: "BRECK", erpName: "BRECK" },
  { webId: "MOAK-ARGONAUTS-BLACK", erpProductId: "cmjsn3hk60003flka3474nygw", erpSku: "ARGO", erpName: "ARGONAUTS" },
  { webId: "MOAK-KAI-BROWN", erpProductId: "cmjsn3gvi0002flkacl59t4um", erpSku: "KAI", erpName: "KAI" },
  { webId: "MOAK-KRONA-YELLOW", erpProductId: "cmjsn3g4c0001flka9cu25lkw", erpSku: "KRONA", erpName: "KRONA" },
  { webId: "MOAK-320OW-SMOKE", erpProductId: "cmjtw8eys0005b2n2jzgmxeyv", erpSku: "320W/SMOKE", erpName: "320ºW - Smoke" },
  { webId: "MOAK-250OW-HONEY", erpProductId: "cmjx4ym820003vivy5mizqq0f", erpSku: "250W/HONEY", erpName: "250ºW - Honey" },
  { webId: "MOAK-250OW-HAVANA", erpProductId: "cmjx4ylt40002vivyucyegwmm", erpSku: "250W/HAVANA", erpName: "250ºW - Havana" },
  { webId: "MOAK-PANJ-GREEN", erpProductId: "cmjx4yldm0001vivymo701z68", erpSku: "PANJ/GREEN", erpName: "PANJ - Green" },
  { webId: "MOAK-PANJ-BLACK", erpProductId: "cmjx4ykvq0000vivycx2oa40c", erpSku: "PANJ/BLACK", erpName: "PANJ - Black" },
  { webId: "MOAK-HAFT-OLIVE", erpProductId: "cmqi66x8w0000kbvkjrpb0o0p", erpSku: "HAFT/OLIVE", erpName: "HAFT - Olive" },
  { webId: "MOAK-HAFT-SILVER", erpProductId: "cmqi67bdg0001kbvkwa6a47b3", erpSku: "HAFT/SILVER", erpName: "HAFT - Silver" },
  { webId: "MOAK-HAFT-BROWN", erpProductId: "cmqi67kb60002kbvkoxvz8qdh", erpSku: "HAFT/BROWN", erpName: "HAFT - Brown" },
  { webId: "MOAK-DAMN-RAW-WHITE", erpProductId: "cmqi91aul000fw181hu5rrbrm", erpSku: "RAW/WHIT", erpName: "DAMN RAW - White" },
  { webId: "MOAK-DAMN-RAW-BLACK", erpProductId: "cmqi912cb000ew18199ontdae", erpSku: "RAW/BLK", erpName: "DAMN RAW - Black" },
  { webId: "MOAK-DAMN-LOWKEY-HAVANA", erpProductId: "cmqi90kzt000dw181zz6bwzg8", erpSku: "LOWKEY", erpName: "DAMN LOWKEY" },
  { webId: "MOAK-DAMN-CHROME-BLACK", erpProductId: "cmqi901gy000cw181m31msm1x", erpSku: "CHROM/BLK", erpName: "DAMN CHROME" },
  { webId: "MOAK-VECTOR-ONE-GREEN", erpProductId: "cmqi8zhsh000bw181jnxvyfr5", erpSku: "VONE/GREN", erpName: "VECTOR ONE - Green" },
  { webId: "MOAK-VECTOR-ONE-BLACK", erpProductId: "cmqi8z9ip000aw1814tq8cer9", erpSku: "VONE/BLK", erpName: "VECTOR ONE - Black" },
  { webId: "MOAK-DAMN-LURKING-YELLOW", erpProductId: "cmqi8fadf0006gz7p15lfc96v", erpSku: "LURK/TRNSYELLO", erpName: "DAMN LURKING - Trans Yellow" },
  { webId: "MOAK-DAMN-LURKING-GREY", erpProductId: "cmqi8eq000005gz7pi8duud0d", erpSku: "LURK/GREY", erpName: "DAMN LURKING - Grey" },
  { webId: "MOAK-DAMN-NARROW-GREEN", erpProductId: "cmqi8dlyz0004gz7p1nkyt4in", erpSku: "NAROW/GRENYELW", erpName: "DAMN NARROW - Green Yellow" },
  { webId: "MOAK-DAMN-NARROW-GREY", erpProductId: "cmqi8d6az0003gz7pez12mf2r", erpSku: "NAROW/GREY", erpName: "DAMN NARROW - GREY" },
  { webId: "MOAK-DAMN-OBSESSED-YELLOW", erpProductId: "cmqi89eyg0002gz7p8eahy0b6", erpSku: "OBSSD/YLOW", erpName: "DAMN OBSESSED" },
  { webId: "MOAK-DAMN-EXACT-HAVANA", erpProductId: "cmqi88bgt0001gz7pk3ne2apw", erpSku: "EXACT/HVNA", erpName: "DAMN EXACT - Havana" },
  { webId: "MOAK-DAMN-TONAL-BLACK", erpProductId: "cmqi87gtb0000gz7p3j42s739", erpSku: "TONAL/BLK", erpName: "DAMN TONAL - Black" },
  { webId: "MOAK-DAMN-NICHE-YELLOW", erpProductId: "cmqi867v70002mtoceuayc2v1", erpSku: "NICHE/CLRYELLW", erpName: "DAMN NICHE - Clear Yellow" },
  { webId: "MOAK-DAMN-NICHE-BLACK", erpProductId: "cmqi85tty0001mtochzisgy0p", erpSku: "NICHE/BLK", erpName: "DAMN NICHE - Black" },
  { webId: "MOAK-DAMN-VOID-GREEN", erpProductId: "cmqi80bgp0000mtoc3bzrl116", erpSku: "VOID/GREN", erpName: "DAMN VOID - Green" },
  { webId: "MOAK-DAMN-STATIC-TRANSPARENT", erpProductId: "cmqgx7svz0001a73krgr9xltm", erpSku: "STATIC/TRNS", erpName: "DAMN STATIC - Transparent" },
  { webId: "MOAK-DAMN-LOUD-WHITE", erpProductId: "cmqgx5x5200008ly78nswbv87", erpSku: "LOUD/WHITE", erpName: "DAMN LOUD - White" },
  { webId: "MOAK-DAMN-MOODY-RED", erpProductId: "cmqgx2bqv0000a73khl7nxcdk", erpSku: "MOODY/RED", erpName: "DAMN MOODY - Red" },
  { webId: "MOAK-DAMN-FILTERED-HAVANA", erpProductId: "cmqgqi7jr0000ycrewm2rzicp", erpSku: "FILTERED/HAVNA", erpName: "DAMN FILTERED - Havana" },
  { webId: "MOAK-DAMN-OFFLINE-GREEN", erpProductId: "cmqgobewb0001lvvk50ph0j3a", erpSku: "OFFLINE/GREN", erpName: "DAMN OFFLINE - Green" },
  { webId: "MOAK-DAMN-LOUD-BLACK", erpProductId: "cmqgo2xs1000ai19qv8skodi9", erpSku: "LOUD/BLK", erpName: "DAMN LOUD - Black" },
  { webId: "MOAK-DAMN-STATIC-BLACK", erpProductId: "cmqgo2b740009i19qjh3u7fjr", erpSku: "STATIC/BLK", erpName: "DAMN STATIC - Black" },
  { webId: "MOAK-DAMN-MUTED-BLACK", erpProductId: "cmqgo1sxp0008i19qn5so3l7q", erpSku: "MUTED/BLK", erpName: "DAMN MUTED - Black" },
  { webId: "MOAK-DAMN-ARCHIVED-BLACK", erpProductId: "cmqgo1drm0007i19qyac4c5lw", erpSku: "ARCHIVED/BLK", erpName: "DAMN ARCHIVED - Black" },
  { webId: "MOAK-DAMN-MOODY-HAVANA", erpProductId: "cmqgo0xhv0006i19qil8nfx19", erpSku: "MOODY/HVNA", erpName: "DAMN MOODY - Havana" },
  { webId: "MOAK-DAMN-PINNED-BROWN", erpProductId: "cmqgo0jci0005i19qglwi9so4", erpSku: "PINNED/BRWNGREN", erpName: "DAMN PINNED - Brown Green" },
  { webId: "MOAK-DAMN-RARE-BLUE", erpProductId: "cmqgo05pn0004i19qfeqhmo37", erpSku: "RARE/BLKBLU", erpName: "DAMN RARE - Black & Blue" },
  { webId: "MOAK-DAMN-FILTERED-BLACK", erpProductId: "cmqgnzsc50003i19q7wom1dsi", erpSku: "FILTERED/BLK", erpName: "DAMN FILTERED - Black" },
  { webId: "MOAK-DAMN-POSTED-BLACK", erpProductId: "cmqgnz98m0002i19qfvkvlr0o", erpSku: "POSTED/BLK", erpName: "DAMN POSTED - Black" },
  { webId: "MOAK-DAMN-OFFLINE-BLACK", erpProductId: "cmqgnws4s0000i19q1kylhocl", erpSku: "OFFLINE-BLK", erpName: "DAMN OFFLINE - Black" },
];
